[features]
seeds = false
[programs.localnet]
sen_otc_prog = "otcesiq3oV6cDJA2fipi8NjSDyQ9LRkw2okR7kqPamt"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/tuphan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"
